import { type Module, inject } from 'langium';
import { 
    createDefaultModule, 
    createDefaultSharedModule, 
    type DefaultSharedModuleContext, 
    type LangiumServices, 
    type LangiumSharedServices, 
    type PartialLangiumServices
} from 'langium/lsp';
import { 
    ReferenceInfo, 
    Scope,
    DefaultScopeProvider,
    AstUtils
} from 'langium';
import { AirfieldGeneratedModule, AirfieldGeneratedSharedModule } from './generated/module.js';
import { AirfieldValidator, registerValidationChecks } from './airfield-validator.js';
import { isModel, isAccessPath, isInduction } from './generated/ast.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type AirfieldAddedServices = {
    validation: {
        AirfieldValidator: AirfieldValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type AirfieldServices = LangiumServices & AirfieldAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const AirfieldModule: Module<AirfieldServices, PartialLangiumServices & AirfieldAddedServices> = {
    validation: {
        AirfieldValidator: () => new AirfieldValidator()
    },
    references: {
        ScopeProvider: (services) => new AirfieldScopeProvider(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createAirfieldServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Airfield: AirfieldServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        AirfieldGeneratedSharedModule
    );
    const Airfield = inject(
        createDefaultModule({ shared }),
        AirfieldGeneratedModule,
        AirfieldModule
    );
    shared.ServiceRegistry.register(Airfield);
    registerValidationChecks(Airfield);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, Airfield };
}

class AirfieldScopeProvider extends DefaultScopeProvider {
    override getScope(context: ReferenceInfo): Scope {
        const model = AstUtils.getContainerOfType(context.container, isModel);
        if (!model) {
            return super.getScope(context);
        }

        // Scoping for HangarBay references in Induction.bays
        // Provide all bays from the referenced hangar (if available), otherwise all bays
        if (context.property === 'bays') {
            const induction = context.container;
            if (isInduction(induction) && induction.hangar?.ref) {
                const hangar = induction.hangar.ref;
                const baysInHangar = hangar.grid.bays;
                const descriptions = baysInHangar.map(bay => 
                    this.descriptions.createDescription(bay, bay.name)
                );
                return this.createScope(descriptions);
            }
            
            // Fallback: all bays from all hangars
            const allBays = model.hangars.flatMap(h => h.grid.bays);
            const descriptions = allBays.map(bay => 
                this.descriptions.createDescription(bay, bay.name)
            );
            return this.createScope(descriptions);
        }

        // Scoping for HangarDoor references in Induction.door
        // Provide only doors from the referenced hangar
        if (context.property === 'door') {
            const induction = context.container;
            if (isInduction(induction) && induction.hangar?.ref) {
                const hangar = induction.hangar.ref;
                const descriptions = hangar.doors.map(door => 
                    this.descriptions.createDescription(door, door.name)
                );
                return this.createScope(descriptions);
            }
            
            // Fallback: all doors from all hangars
            const allDoors = model.hangars.flatMap(h => h.doors);
            const descriptions = allDoors.map(door => 
                this.descriptions.createDescription(door, door.name)
            );
            return this.createScope(descriptions);
        }

        // Scoping for AccessNode references in HangarDoor.accessNode and HangarBay.accessNode
        // Provide all access nodes from all access paths
        if (context.property === 'accessNode') {
            const allNodes = model.accessPaths.flatMap(ap => ap.nodes);
            const descriptions = allNodes.map(node => 
                this.descriptions.createDescription(node, node.name)
            );
            return this.createScope(descriptions);
        }

        // Scoping for AccessNode references in AccessLink (from/to)
        // Provide nodes from the same AccessPath
        if (context.property === 'from' || context.property === 'to') {
            const accessPath = AstUtils.getContainerOfType(context.container, isAccessPath);
            if (accessPath) {
                const descriptions = accessPath.nodes.map(node => 
                    this.descriptions.createDescription(node, node.name)
                );
                return this.createScope(descriptions);
            }
        }

        // Scoping for precedingInductions in AutoInduction
        // Allow references to both Induction and AutoInduction
        if (context.property === 'precedingInductions') {
            const allInductions = [...model.inductions, ...model.autoInductions];
            const descriptions = allInductions
                .filter(ind => ind.id) // Only allow references to inductions with explicit IDs
                .map(ind =>
                    this.descriptions.createDescription(ind, ind.id!)
                );
            return this.createScope(descriptions);
        }

        return super.getScope(context);
    }
}
